database: &default
    adapter: sqlite3
    database: db.sqlite

production:
    adapter: postgresql
    database: <%= ENV['DATABASE_NAME'] %>
    username: <%= ENV['DATABASE_USER'] %>
    password: <%= ENV['DATABASE_PASS'] %>
