database: &default
    adapter: postgresql
    url: postgres://@localhost/bandejao-bot

development:
    <<: *default

test:
    <<: *default
    url: postgres://@localhost/bandejao-bot-test

production:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
