database: &default
    adapter: sqlite3
    database: db.sqlite

production:
    <<: *default
    adapter: postgresql
    database: BANDEJAO_BOT_DATABASE
    password: <%= ENV['BANDEJAO_BOT_DATABASE_PASSWORD'] %>
